#!/bin/bash

## Progress-Aware-Scheduler implementation
## Author: Manel Lurbe Sempere
## Year: 2021

echo ''
echo 'Progress-Aware-Scheduler implementation. Year: 2021 Author: Manel Lurbe Sempere <malursem@gap.upv.es>.'
echo ''

if cp -rf Makefile ../libpfm-4.10.1/perf_examples/ ; then
    if cp -rf PAS.c ../libpfm-4.10.1/perf_examples/ ; then
        if cd ../libpfm-4.10.1/perf_examples ; then
            echo \#Actual directory:\#
            pwd
            echo ""
            echo \#Compiling programs...\#
            echo ""
            if make ; then
                echo ""
                echo \#Programs compiled without errors.\#
                echo ""
                if cp -rf PAS ../../ ; then
                        echo ""
                        echo \#Programs copied to working_dir.\#
                        echo ""
                else
                        echo ""
                        echo \#Error coping compiled programs.\#
                        echo ""
                fi
            else
                echo ""
                echo \#Error compiling programs.\#
                echo ""
            fi
        else 
            echo ""
            echo \#Error could not access to the directory.\#
            echo ""
        fi
    else
        echo ""
        echo \#Error coping .c codes.\#
        echo ""
    fi
else
    echo ""
    echo \#Error coping Makefile.\#
    echo ""
fi
